### PR TITLE
Fixed Niak tools

### PR DESCRIPTION
**Pull request by glatard**

### CODE REVIEW

**Comment by gkiar** [comment]
ouf the diff is super ugly with Python writing of JSONS - perhaps now the order will be static though for future iterations, as Python seems to write elements alphabetically.

Do we want to make the singularity-hub link "clickable"? I.e. it's a docker container, we could recognize that and provide a url like `hub.docker.com/r/simexp/niak-cog` that brings users to the web page, since the descriptor has the correct notation anyways, this may be easier for people? If you agree, I can make this change in publish.

**Comment by glatard** [comment]
yes, I used `sort_keys = True` in `json.dumps`. 

I'm confused about those `docker://` URLs in singularity container definitions. If I understand well, they're only here to tell CBRAIN to use Singularity to run Docker containers. Shouldn't the Boutiques descriptor contain a Docker image in this case? It should be up to the platform to choose whether it wants to run Docker natively or through Singularity.

**Comment by gkiar** [comment]
The `docker://` is how `singularity pull` would access containers on dockerhub - so if you want to run it through singularity you can always pull from dockerhub and convert. The opposite is not true. I would prefer if, in general, we did as you said and restricted singularity url to be for containers on singularity hub itself, but this is a CBRAINism currently.

**Comment by glatard** [comment]
can we change that in CBRAIN before we have to handle 'docker://' prefixes everywhere else?

**Comment by gkiar** [comment]
I mean, singularity handles it, we don't need to do anything. I agree it'd be nicer if they were genuine singularity urls, but I don't see it as any overhead for us to let `docker://` urls exist in singularity container indices, perhaps it just indicates the container is supported by both? Not all docker containers can automatically be ported to sing

**Pull request merged**
